// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: darknetserver.proto
#ifndef GRPC_darknetserver_2eproto__INCLUDED
#define GRPC_darknetserver_2eproto__INCLUDED

#include "darknetserver.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace darknetServer {

class ImageDetection final {
 public:
  static constexpr char const* service_full_name() {
    return "darknetServer.ImageDetection";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RequestDetection(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::darknetServer::DetectedObjects* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::darknetServer::DetectedObjects>> AsyncRequestDetection(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::darknetServer::DetectedObjects>>(AsyncRequestDetectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::darknetServer::DetectedObjects>> PrepareAsyncRequestDetection(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::darknetServer::DetectedObjects>>(PrepareAsyncRequestDetectionRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::darknetServer::DetectedObjects>* AsyncRequestDetectionRaw(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::darknetServer::DetectedObjects>* PrepareAsyncRequestDetectionRaw(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RequestDetection(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::darknetServer::DetectedObjects* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::darknetServer::DetectedObjects>> AsyncRequestDetection(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::darknetServer::DetectedObjects>>(AsyncRequestDetectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::darknetServer::DetectedObjects>> PrepareAsyncRequestDetection(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::darknetServer::DetectedObjects>>(PrepareAsyncRequestDetectionRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::darknetServer::DetectedObjects>* AsyncRequestDetectionRaw(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::darknetServer::DetectedObjects>* PrepareAsyncRequestDetectionRaw(::grpc::ClientContext* context, const ::darknetServer::KeyFrame& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestDetection_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestDetection(::grpc::ServerContext* context, const ::darknetServer::KeyFrame* request, ::darknetServer::DetectedObjects* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RequestDetection() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const ::darknetServer::KeyFrame* request, ::darknetServer::DetectedObjects* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestDetection(::grpc::ServerContext* context, ::darknetServer::KeyFrame* request, ::grpc::ServerAsyncResponseWriter< ::darknetServer::DetectedObjects>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestDetection<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RequestDetection() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const ::darknetServer::KeyFrame* request, ::darknetServer::DetectedObjects* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_RequestDetection() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const ::darknetServer::KeyFrame* request, ::darknetServer::DetectedObjects* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestDetection(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RequestDetection() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>(std::bind(&WithStreamedUnaryMethod_RequestDetection<BaseClass>::StreamedRequestDetection, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const ::darknetServer::KeyFrame* request, ::darknetServer::DetectedObjects* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestDetection(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::darknetServer::KeyFrame,::darknetServer::DetectedObjects>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestDetection<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestDetection<Service > StreamedService;
};

}  // namespace darknetServer


#endif  // GRPC_darknetserver_2eproto__INCLUDED
