// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: darknetserver.proto
#ifndef GRPC_darknetserver_2eproto__INCLUDED
#define GRPC_darknetserver_2eproto__INCLUDED

#include "darknetserver.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace darknetServer {

class ImageDetection final {
 public:
  static constexpr char const* service_full_name() {
    return "darknetServer.ImageDetection";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>> requestDetection(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>>(requestDetectionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>> AsyncrequestDetection(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>>(AsyncrequestDetectionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>> PrepareAsyncrequestDetection(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>>(PrepareAsyncrequestDetectionRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* requestDetectionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* AsyncrequestDetectionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* PrepareAsyncrequestDetectionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>> requestDetection(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>>(requestDetectionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>> AsyncrequestDetection(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>>(AsyncrequestDetectionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>> PrepareAsyncrequestDetection(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>>(PrepareAsyncrequestDetectionRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* requestDetectionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* AsyncrequestDetectionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* PrepareAsyncrequestDetectionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_requestDetection_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status requestDetection(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::darknetServer::DetectedObjects, ::darknetServer::KeyFrame>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_requestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_requestDetection() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_requestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestDetection(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::darknetServer::DetectedObjects, ::darknetServer::KeyFrame>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestDetection(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::darknetServer::DetectedObjects, ::darknetServer::KeyFrame>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_requestDetection<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_requestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_requestDetection() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_requestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestDetection(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::darknetServer::DetectedObjects, ::darknetServer::KeyFrame>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_requestDetection() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_requestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestDetection(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::darknetServer::DetectedObjects, ::darknetServer::KeyFrame>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestDetection(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace darknetServer


#endif  // GRPC_darknetserver_2eproto__INCLUDED
