// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: darknetserver
#ifndef GRPC_darknetserver__INCLUDED
#define GRPC_darknetserver__INCLUDED

#include "darknetserver_generated.h"
#include "flatbuffers/grpc.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace darknetServer {

class ImageDetection final {
 public:
  static constexpr char const* service_full_name() {
    return "darknetServer.ImageDetection";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, flatbuffers::grpc::Message<DetectedObjects>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<DetectedObjects>>> AsyncRequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<DetectedObjects>>>(AsyncRequestDetectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<DetectedObjects>>> PrepareAsyncRequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<DetectedObjects>>>(PrepareAsyncRequestDetectionRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<DetectedObjects>>* AsyncRequestDetectionRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<DetectedObjects>>* PrepareAsyncRequestDetectionRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, flatbuffers::grpc::Message<DetectedObjects>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>> AsyncRequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>>(AsyncRequestDetectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>> PrepareAsyncRequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>>(PrepareAsyncRequestDetectionRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>* AsyncRequestDetectionRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>* PrepareAsyncRequestDetectionRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestDetection_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestDetection(::grpc::ServerContext* context, const flatbuffers::grpc::Message<KeyFrame>* request, flatbuffers::grpc::Message<DetectedObjects>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RequestDetection() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const flatbuffers::grpc::Message<KeyFrame>* request, flatbuffers::grpc::Message<DetectedObjects>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestDetection(::grpc::ServerContext* context, flatbuffers::grpc::Message<KeyFrame>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<DetectedObjects>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_RequestDetection<  Service   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RequestDetection() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const flatbuffers::grpc::Message<KeyFrame>* request, flatbuffers::grpc::Message<DetectedObjects>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RequestDetection() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<KeyFrame>, flatbuffers::grpc::Message<DetectedObjects>>(std::bind(&WithStreamedUnaryMethod_RequestDetection<BaseClass>::StreamedRequestDetection, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RequestDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestDetection(::grpc::ServerContext* context, const flatbuffers::grpc::Message<KeyFrame>* request, flatbuffers::grpc::Message<DetectedObjects>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestDetection(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<KeyFrame>,flatbuffers::grpc::Message<DetectedObjects>>* server_unary_streamer) = 0;
  };
  typedef   WithStreamedUnaryMethod_RequestDetection<  Service   >   StreamedUnaryService;
  typedef   Service   SplitStreamedService;
  typedef   WithStreamedUnaryMethod_RequestDetection<  Service   >   StreamedService;
};

}  // namespace darknetServer


#endif  // GRPC_darknetserver__INCLUDED
