// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: darknetserver

#include "darknetserver_generated.h"
#include "darknetserver.grpc.fb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace darknetServer {

static const char* ImageDetection_method_names[] = {
  "/darknetServer.ImageDetection/RequestDetection",
};

std::unique_ptr< ImageDetection::Stub> ImageDetection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< ImageDetection::Stub> stub(new ImageDetection::Stub(channel));
  return stub;
}

ImageDetection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel)  , rpcmethod_RequestDetection_(ImageDetection_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}
  
::grpc::Status ImageDetection::Stub::RequestDetection(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, flatbuffers::grpc::Message<DetectedObjects>* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RequestDetection_, context, request, response);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>* ImageDetection::Stub::AsyncRequestDetectionRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<DetectedObjects>>::Create(channel_.get(), cq, rpcmethod_RequestDetection_, context, request, true);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<DetectedObjects>>* ImageDetection::Stub::PrepareAsyncRequestDetectionRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<KeyFrame>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<DetectedObjects>>::Create(channel_.get(), cq, rpcmethod_RequestDetection_, context, request, false);
}

ImageDetection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageDetection_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageDetection::Service, flatbuffers::grpc::Message<KeyFrame>, flatbuffers::grpc::Message<DetectedObjects>>(
          std::mem_fn(&ImageDetection::Service::RequestDetection), this)));
}

ImageDetection::Service::~Service() {
}

::grpc::Status ImageDetection::Service::RequestDetection(::grpc::ServerContext* context, const flatbuffers::grpc::Message<KeyFrame>* request, flatbuffers::grpc::Message<DetectedObjects>* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace darknetServer

