// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: darknetserver.proto

#include "darknetserver.pb.h"
#include "darknetserver.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace darknetServer {

static const char* ImageDetection_method_names[] = {
  "/darknetServer.ImageDetection/requestDetection",
};

std::unique_ptr< ImageDetection::Stub> ImageDetection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageDetection::Stub> stub(new ImageDetection::Stub(channel));
  return stub;
}

ImageDetection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_requestDetection_(ImageDetection_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* ImageDetection::Stub::requestDetectionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>::Create(channel_.get(), rpcmethod_requestDetection_, context);
}

::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* ImageDetection::Stub::AsyncrequestDetectionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>::Create(channel_.get(), cq, rpcmethod_requestDetection_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>* ImageDetection::Stub::PrepareAsyncrequestDetectionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>::Create(channel_.get(), cq, rpcmethod_requestDetection_, context, false, nullptr);
}

ImageDetection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageDetection_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ImageDetection::Service, ::darknetServer::KeyFrame, ::darknetServer::DetectedObjects>(
          std::mem_fn(&ImageDetection::Service::requestDetection), this)));
}

ImageDetection::Service::~Service() {
}

::grpc::Status ImageDetection::Service::requestDetection(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::darknetServer::DetectedObjects, ::darknetServer::KeyFrame>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace darknetServer

